/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OverallStats = IDL.Record({
  'totalDuration' : IDL.Nat,
  'overallAverageScore' : IDL.Nat,
  'totalSessions' : IDL.Nat,
});
export const Time = IDL.Int;
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : Time,
  'score' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'notes' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'color' : IDL.Text,
});
export const SubjectStats = IDL.Record({
  'scoreDelta' : IDL.Int,
  'subject' : Subject,
  'totalDuration' : IDL.Nat,
  'lastScore' : IDL.Nat,
  'sessionCount' : IDL.Nat,
  'averageScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOverallStats' : IDL.Func([], [OverallStats], ['query']),
  'getRecentSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getSessionsForSubject' : IDL.Func([IDL.Nat], [IDL.Vec(Session)], ['query']),
  'getSubjectStats' : IDL.Func([IDL.Nat], [SubjectStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'logSession' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OverallStats = IDL.Record({
    'totalDuration' : IDL.Nat,
    'overallAverageScore' : IDL.Nat,
    'totalSessions' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : Time,
    'score' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'color' : IDL.Text,
  });
  const SubjectStats = IDL.Record({
    'scoreDelta' : IDL.Int,
    'subject' : Subject,
    'totalDuration' : IDL.Nat,
    'lastScore' : IDL.Nat,
    'sessionCount' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOverallStats' : IDL.Func([], [OverallStats], ['query']),
    'getRecentSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getSessionsForSubject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Session)],
        ['query'],
      ),
    'getSubjectStats' : IDL.Func([IDL.Nat], [SubjectStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'logSession' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };