/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OverallStats {
  'totalDuration' : bigint,
  'overallAverageScore' : bigint,
  'totalSessions' : bigint,
}
export interface Session {
  'id' : bigint,
  'date' : string,
  'createdAt' : Time,
  'score' : bigint,
  'durationMinutes' : bigint,
  'subjectId' : bigint,
  'notes' : string,
}
export interface Subject {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'color' : string,
}
export interface SubjectStats {
  'scoreDelta' : bigint,
  'subject' : Subject,
  'totalDuration' : bigint,
  'lastScore' : bigint,
  'sessionCount' : bigint,
  'averageScore' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSubject' : ActorMethod<[string, string], bigint>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOverallStats' : ActorMethod<[], OverallStats>,
  'getRecentSessions' : ActorMethod<[], Array<Session>>,
  'getSessionsForSubject' : ActorMethod<[bigint], Array<Session>>,
  'getSubjectStats' : ActorMethod<[bigint], SubjectStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSubjects' : ActorMethod<[], Array<Subject>>,
  'logSession' : ActorMethod<[bigint, string, bigint, bigint, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];